# Generated by Django 4.1.7 on 2023-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="card_password",
            field=models.CharField(max_length=100),
        ),
    ]
