# Generated by Django 4.1.7 on 2023-05-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customer_card_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="customer_id", new_name="id",
        ),
    ]
