# Generated by Django 4.1.7 on 2023-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_customer_id_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="create_time",
            field=models.CharField(default="YYYY-MM-DD HH:MM:SS.ssssss", max_length=50),
            preserve_default=False,
        ),
    ]
