# Generated by Django 4.1.7 on 2023-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_invoice_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="card_number", field=models.IntegerField(),
        ),
    ]
