# Generated by Django 4.1.7 on 2023-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customer_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="card_number", field=models.BigIntegerField(),
        ),
    ]
