# Generated by Django 4.1.7 on 2023-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_customer_token_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="token_time",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="create_time",
            field=models.CharField(default="2023-05-11 10:13:22.046348", max_length=50),
            preserve_default=False,
        ),
    ]
