# Generated by Django 4.1.7 on 2023-05-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customer_token_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="balance",
            field=models.DecimalField(decimal_places=2, default="", max_digits=10),
        ),
    ]
