# Generated by Django 4.1.7 on 2023-05-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_customer_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="access_token", new_name="token",
        ),
    ]
