# Generated by Django 4.1.7 on 2023-05-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0016_rename_access_token_customer_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="customer_set",
                related_query_name="customer",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customer_set",
                related_query_name="customer",
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="accounts.customer",
            ),
        ),
    ]
