# Generated by Django 4.1.7 on 2023-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="phone", field=models.CharField(max_length=30),
        ),
    ]
