# Generated by Django 4.1.7 on 2023-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bank_account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
